### ISSUE TITLE
Help needed: Stunt Rally Flatpak (move to Ogre 1.13.4)

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally#67]
Hello, I apologize for creating this as a ticket in the Stunt Rally repo, however it is related. I am trying to update the [Flatpak](https://flatpak.org) version of Stunt Rally to a new build with more recent libraries/Flatpak runtime, but sadly it has build errors that I am not able to resolve. I would highly appreciate any help.

If interested, please see the related PR: https://github.com/flathub/org.tuxfamily.StuntRally/pull/7

If the problems are resolved, many Linux gamers will benefit from this. As a bonus, Stunt Rally will also be in a great shape on [Steam Deck](https://www.steamdeck.com) (it is already available in the Flathub repo that Steam Deck has enabled out-of-box, but the current version of Stunt Rally Flatpak is too old to work properly there). If not, the Stunt Rally Flatpak will probably get removed from Flathub.

**edit:** See https://github.com/stuntrally/stuntrally/issues/67#issuecomment-1245309710.

**Comment by cryham** [comment]
Hi AsciiWolf
I see, but I'm new to this, where are any errors?
What fails there? Is it only because of #29 #30 #31?
Which SR hash does it build from, the 2.6.2 version? If so, can you try latest master?
I want to update to Ogre 1.13 and make a release soon.

**Comment by AsciiWolf** [comment]
Hi cryham,

here is the full build log: https://buildbot.flathub.org/#/builders/48/builds/11863/steps/6/logs/stdio

It builds from 2.6.2. I have tried latest master a week or two ago and there was the same issue there.

The Flatpak is building with OGRE 13.3.4, so this may be a problem is Stunt Rally is not fully compatible with OGRE 13.x yet.

**Comment by AsciiWolf** [comment]
Any news about the new Stunt Rally release? :-)

**Comment by cryham** [comment]
Well there is a stupid bug, at least in Windows binaries with Ogre 1.13.4 that crashes game and editor on next track load. I think I broke something with resources unloading for road. Have to fix it before release.
Few smaller bugs listed here https://github.com/stuntrally/stuntrally/pull/39#issuecomment-1188905640
SR 2.7 gallery is done, I'm finishing new 2.7 video.

**Comment by AsciiWolf** [comment]
Current issues:
https://github.com/stuntrally/stuntrally/issues/30
https://github.com/stuntrally/stuntrally/issues/31#issuecomment-1245268345
https://github.com/stuntrally/stuntrally/issues/84

**Comment by cryham** [comment]
#83 (for #84), the 1st critical thing to fix

**Comment by AsciiWolf** [comment]
#31 is probably the only true remaining blocker preventing me from updating the Flatpak since it makes the game unplayable. The other two issues are annoying, but not that serious.

**Comment by cryham** [comment]
Allright since #83 got fixed just now, and #31 was fixed with Release build, could you try testing latest SR build?
I'm going to tag and release 2.7 soon. Seems stable again, with Ogre 1.13.4.

**Comment by AsciiWolf** [comment]
@cryham Thanks! :-) I have [updated](https://github.com/flathub/org.tuxfamily.StuntRally/pull/7#event-7748051407) the Pull Request, test build should be ready in a few hours. I will try it tomorrow.

**Comment by AsciiWolf** [comment]
The crash on next track loading really looks to be fixed. :-) #30 is still present, but can be worked around by selecting the resolution first and clicking the "Change" button, then checking the "Full Screen" checkbox.

By the way, #31 is fixed for most maps now, but there is still quite a lot of stuttering on some of them (for example on the `Autumn` map).

**Comment by cryham** [comment]
Just tagged 2.7 release.
